import React from "react";
import Head from 'next/head'
import Header from "./Header";
import Footer from "./Footer";
const Layout = ({children,title,guitarras}) => {
  return <>
		  <Head>
        <title>Tienda de guitarras - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" /> 
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </Head>
      <Header guitarras={guitarras}/>
			{children}
      <Footer />
	</>;
};

export default Layout;
