import React from "react";
import Layout from "../components/Layout";
import Link from "next/link";
import Head from "next/head";
import styles from '../styles/NotFound.module.css'
const notFound = () => {
  return (
		<>
			<Head>
				<title>404 not found</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.no_encontrado}>
				<h1 className="heading">pagina no encontrada</h1>
				<Link href="/">Volver al inicio</Link>
			</div>
			</>
  );
};

export default notFound;
